Add CMakeLists.txt
xiph/opusfile pull request #25
Opened 2021-05-28 17:01 UTC by h3ndrk

This PR adds CMake support for opusfile and opusurl. autotools is untouched.

Fixes #15

Currently this PR is still WIP, TODOs are written in changed files. Advice for solving the TODOs and general feedback is desired!

2021-05-29 16:50 UTC, h3ndrk commented
This PR is ready for review. Some questions to the authors:

1. Currently the version is hard-coded in the `CMakeLists.txt`. How is your normal workflow for embedding it into the library and distribution files etc.? I only had a brief look at the many scripts that somehow mutate and propagate the version. It seems very complex tooling for the job... Maybe there is a simple way that I don't see currently?
2. Do we want to also build the documentation with CMake? There is also another problem with it, see #21

Thanks!

2021-05-29 18:20 UTC, rillian commented
> I only had a brief look at the many scripts that somehow mutate and propagate the version. It seems very complex tooling for the job...

Yes, this is pretty complicated. The requirements are:

- When building from a repository, the software version should be derived from `git describe --tags` for clarity and correctness.
- When building from a release source package, where no revision history is available, the version should be set statically.
- Version info needs to be propagated to:
  - config.h for use in the library
  - pkg-config files describing the library
  - source package naming
  - documentation

That way we get something like `0.12` for a release but `0.12-6-g641bf7e` the current development tree.

There's a unix shell script `update_version` which queries git and writes the result to a file `package_version` which is read by various build systems. This file isn't tracked by git, but is included in release source packages. Together that covers the static and dynamic version requirements.

Now, opusfile library code doesn't currently *use* the `PACKAGE_VERSION` define, cmake doesn't create pkg-config files or source packages, so you'd only need this for documentation, if you add support for building that (which would be nice). However, opusfile might use the version string at some point in the future, so a cmake build should support it.

You can't call the unix shell script on Windows. I suggest copying `cmake/OpusPackageVersion.cmake` from the opus repo, which re-implements the script in cmake.

2021-05-29 18:33 UTC, rillian requested changes
I'd like to see the version TODO addressed, and some ci converage before this lands. Building the documentation would be nice, but can also be a separate PR. Otherwise I looks fine to me.

@evpobr, @xnorpx do you have any comments?

2021-05-29 21:39 UTC, xnorpx commented
I can take a look next week. 

Do you need cmake_minimum_required(VERSION 3.16) ?

(people with  old linux distros always complain with high cmake versions :) )

2021-05-31 15:33 UTC, h3ndrk commented
> Do you need cmake_minimum_required(VERSION 3.16) ?
> 
> (people with old linux distros always complain with high cmake versions :) )

I've only tested with CMake 3.16 (officially available on Ubuntu 20.04) and I know at least one feature (timestamping of Doxygen) which requires 3.16. But compatibility vs. modern features is always a hard question... In the book [Professional CMake](https://crascit.com/professional-cmake/), the author says that it is preferred to not limit the project maintainers in functionality caused by old CMake versions but rather require users to download a more recent version of CMake themselves (which is very easy).

> I'd like to see the version TODO addressed

Done, version is retrieved via a CMake module taken from opus.

> Building the documentation would be nice

Done with changing behavior: The output paths change because I would like to use the official [`FindDoxygen.cmake`](https://cmake.org/cmake/help/latest/module/FindDoxygen.html) module which makes integrating Doxygen very easy in CMake. The module generates a `Doxyfile` automatically and outputs the documentation into a subdirectory in the build directory which means the `Doxygen.in` file is obsolete and documentation is generated not in the `doc/` directory.

> some ci converage before this lands

Currently, there is no CMake find module for opus and ogg which means that the `CMakeLists.txt` of opusfile will only work with opus and ogg installed with CMake configs instead of legacy pkgconfig. Not installing CMake configs is quite common in most distributions sadly (the Travis CI also has this problem). I will try to come up with some find modules relying on CMake configs and pkgconfig as a fallback. I've no experience how opusfile is built on Windows and how it finds its dependencies there. I will add some CI steps after the find modules are done.

2021-05-31 19:14 UTC, h3ndrk commented
- Find modules added
- Travis CI passing
- The same commands added to GitLab CI

2021-05-31 21:17 UTC, rillian commented on .gitlab-ci.yml
> +    - wget https://cmake.org/files/v3.16/cmake-3.16.9-Linux-x86_64.tar.gz
Thanks for adding a CI config. That's nice to see, and these steps are [green on our gitlab](https://gitlab.xiph.org/xiph/opusfile/-/jobs/11755).

Pulling a binary like this is unfortunate. It makes the build description specific to x86_64-linux, so at the very least you need an arch-specific tag.

The `gcc:9` container we use is based on `debian:10` which has cmake 3.13.3, and is used by all our other gitlab ci jobs. Is that also too old? See, I'm already complaining about the aggressive cmake version. :)

There's a `kitware/cmake` container feed on docker hub (just as huge as the gcc images!) but it seems to just be their internal ci runners, rather than something for external use. At least, I couldn't make sense of the versioning for that.

2021-05-31 21:27 UTC, rillian commented on .travis.yml
> +      wget https://cmake.org/files/v3.16/cmake-3.16.9-Linux-x86_64.tar.gz;
You can use `curl -O` here to avoid having to install `wget`.

2021-06-01 04:46 UTC, evpobr commented on CMakeLists.txt
> +    $<$<BOOL:OP_HAVE_LIBM>:m>
`$<$<BOOL:${OP_HAVE_LIBM}>:m>`

2021-06-01 04:57 UTC, evpobr commented
> I've only tested with CMake 3.16 (officially available on Ubuntu 20.04) and I know at least one feature (timestamping of Doxygen) which requires 3.16. But compatibility vs. modern features is always a hard question... In the book [Professional CMake](https://crascit.com/professional-cmake/), the author says that it is preferred to not limit the project maintainers in functionality caused by old CMake versions but rather require users to download a more recent version of CMake themselves (which is very easy).

In theory it is correct. In practice version it is too high for some Linux distros. It's surprising to me that someone is using such old distros, but i have encountered similar reports on a regular basis.

I could recommend to use more or less safe version (e.g. 3.6) and enable features depending on `CMAKE_VERSION` checks. You can display message if some feature is disabled because CMake version is too low.

2021-06-01 05:04 UTC, evpobr commented on CMakeLists.txt
> +    check_include_file("winsock2.h" OP_HAVE_WINSOCK2_H)
winsock2 is from Win95 times, not sure it is required to check it today.

2021-06-01 06:01 UTC, xnorpx commented on CMakeLists.txt
> +    $<$<C_COMPILER_ID:Clang,GNU>:-std=c89>
use https://cmake.org/cmake/help/v3.1/prop_tgt/C_STANDARD.html ?

2021-06-04 18:36 UTC, h3ndrk commented on CMakeLists.txt
> +    $<$<C_COMPILER_ID:Clang,GNU>:-std=c89>
I'd propose to just omit that compiler flag because [`C_STANDARD`](https://cmake.org/cmake/help/latest/prop_tgt/C_STANDARD.html) does not seem to support any value for C89. Maybe that is already default?

2021-06-04 18:39 UTC, h3ndrk commented on CMakeLists.txt
> +    check_include_file("winsock2.h" OP_HAVE_WINSOCK2_H)
I tried to do a nearly exact port of the autoconf/autotools scripts. Since I don't have access to Windows please say more directly how we should proceed here. Should I just remove the check?

2021-06-04 18:39 UTC, h3ndrk commented on .travis.yml
> +      wget https://cmake.org/files/v3.16/cmake-3.16.9-Linux-x86_64.tar.gz;
Done

2021-06-04 18:39 UTC, h3ndrk commented on CMakeLists.txt
> +    $<$<BOOL:OP_HAVE_LIBM>:m>
Done

2021-06-04 19:06 UTC, h3ndrk commented
> I could recommend to use more or less safe version (e.g. 3.6) and enable features depending on CMAKE_VERSION checks. You can display message if some feature is disabled because CMake version is too low.

Testing and back-porting the CMake scripts is a lot of effort because

1. ... there are things that don't exist in older versions. I don't have much motivation to re-implement things that already exist in newer versions.
2. ... back-porting can lead to nasty bugs in CMake without helpful error messages. See https://alexreinking.com/blog/how-to-use-cmake-without-the-agonizing-pain-part-1.html (section "Validating Your Minimum Version").
3. ... manually figuring out what features are needed from newer versions and implementing reasonable fallbacks is complicated and error-prone.

These points are also argued by CMake experts, saying that developers of CMake build systems should not try to support very old versions but rather require the version that they have developed on.

Because of these reasons I would like to keep `cmake_minimum_required(VERSION 3.16)`.

2021-06-04 19:06 UTC, h3ndrk commented on .gitlab-ci.yml
> +    - wget https://cmake.org/files/v3.16/cmake-3.16.9-Linux-x86_64.tar.gz
I'm not sure what you mean with *arch-specific tag*. Could you elaborate on this?

I also found [`rikorose/gcc-cmake`](https://hub.docker.com/r/rikorose/gcc-cmake/), but it is third-party and I'm not sure if you want to rely on that.

Regarding the CMake version, see my comment below.

2021-06-04 19:35 UTC, petterreinholdtsen commented
While I agree that it is good to have conservative build dependencies,
to help those that do not have luxury of trying the latest and less
tested versions of software, I thought it might be useful with a data
point on cmake versions in Debian.  From
<URL: https://tracker.debian.org/pkg/cmake > it can be seen that
oldstable (9) is the version of Debian with cmake < 3.16.  Stable and
newer have =< 3.16.  Is it known which distributions and versions will
be locked out by depending on 3.16?

-- 
Happy hacking
Petter Reinholdtsen

2021-06-04 19:51 UTC, h3ndrk commented
Maybe have a look at https://gitlab.kitware.com/cmake/community/-/wikis/CMake-Versions-on-Linux-Distros or https://gitlab.kitware.com/cmake/community/-/wikis/CMake-Versions-on-Linux-Distros.

2021-06-05 07:09 UTC, evpobr commented on CMakeLists.txt
> +    check_include_file("winsock2.h" OP_HAVE_WINSOCK2_H)
Yep.

2021-06-05 07:23 UTC, evpobr commented
https://repology.org/project/cmake/versions

2021-06-05 09:54 UTC, h3ndrk commented on CMakeLists.txt
> +    check_include_file("winsock2.h" OP_HAVE_WINSOCK2_H)
Done

2021-06-06 03:52 UTC, Be-ing commented
Thanks for working on this! It will make this library easier to use, especially on Windows.

2021-06-28 12:41 UTC, h3ndrk commented
Ping

2021-06-28 15:28 UTC, evpobr requested changes

2021-06-28 15:28 UTC, evpobr commented on CMakeLists.txt
> +  PUBLIC_HEADER DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}"
Should it be `${CMAKE_INSTALL_INCLUDEDIR}/opus`?

https://packages.debian.org/sid/amd64/libopusfile-dev/filelist

2021-07-02 08:19 UTC, h3ndrk commented on CMakeLists.txt
> +  PUBLIC_HEADER DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}"
Is it correct that we install in `/usr/include/opus` instead of `/usr/include/opusfile`?

2021-07-02 08:56 UTC, evpobr commented on CMakeLists.txt
> +  PUBLIC_HEADER DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}"
I guess so:

https://github.com/xiph/opusfile/blob/56728646d626791b08d2b15af0147fb9d0d27bf7/Makefile.am#L7

And public include directory should be `${CMAKE_INSTALL_INCLUDEDIR}/include/opus`:

https://github.com/xiph/opusfile/blob/56728646d626791b08d2b15af0147fb9d0d27bf7/examples/opusfile_example.c#L25

2021-07-02 09:59 UTC, h3ndrk commented on CMakeLists.txt
> +  PUBLIC_HEADER DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}"
Done. You wrote `${CMAKE_INSTALL_INCLUDEDIR}/include/opus`, I put it in `${CMAKE_INSTALL_INCLUDEDIR}/opus`. I hope this is fine.

2021-07-02 10:16 UTC, evpobr commented on CMakeLists.txt
> +  PUBLIC_HEADER DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}"
Yes, you're right.

2022-01-14 18:05 UTC, Yohannfra commented
Hi, any news for this PR ?

2022-01-15 09:31 UTC, evpobr approved these changes

2022-01-15 19:12 UTC, rillian approved these changes

2022-01-15 19:14 UTC, rillian commented
Merged upstream in cf218fb54929a1f54e30e2cb208a22d08b08c889. Thanks!

2022-01-15 19:14 UTC, closed without merging